version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
    - POSTGRES_DB=my_store
    - POSTGRES_USER=tonny
    - POSTGRES_PASSWORD=admin123
    ports:
    - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tonyoanthony@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=tonny187
    ports:
      - 5050:80
